In [1]:
!pip install langchain_huggingface

In [6]:
from langchain_huggingface import HuggingFaceEmbeddings
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

embedding_name = 'HooshvareLab/bert-fa-base-uncased'
embeddings = HuggingFaceEmbeddings(model_name=embedding_name)

texts = [
    "هوش مصنوعی در حال تغییر جهان است.",
    "فناوری هوش مصنوعی زندگی انسان‌ها را دگرگون می‌کند.",
    "رانندگی علی خوب است"
]

vectors = [embeddings.embed_query(text) for text in texts]
vectors_np = np.array(vectors)

cos_sim_matrix = cosine_similarity(vectors_np)
print(cos_sim_matrix)


config.json:   0%|          | 0.00/440 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/654M [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/654M [00:00<?, ?B/s]

[[1.         0.82357448 0.57357651]
 [0.82357448 1.         0.56830832]
 [0.57357651 0.56830832 1.        ]]


In [5]:
from sentence_transformers import SentenceTransformer, util
import numpy as np

model = SentenceTransformer('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2')

texts = [
    "هوش مصنوعی در حال تغییر جهان است.",
    "فناوری هوش مصنوعی زندگی انسان‌ها را دگرگون می‌کند.",
    "رانندگی علی خوب است"
]

vectors = model.encode(texts, convert_to_numpy=True)
cos_sim_matrix = util.cos_sim(vectors, vectors).numpy()

print(cos_sim_matrix)


modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

[[0.9999999  0.87920356 0.08984164]
 [0.87920356 1.         0.07217301]
 [0.08984164 0.07217302 1.0000001 ]]
